
import '../models/authenticate/user%20model.dart';

import '../models/language/language.dart';
import '../models/notification/notification.dart';
import '../models/other/banner model.dart';
import '../models/other/screens.dart';
import '../models/other/setting model.dart';
import '../models/other/side menu.dart';
import '../models/programmer/programmer.dart';
import '../models/statistics/articles.dart';
import '../models/statistics/matches scores.dart';
import '../models/statistics/player.dart';
import '../models/statistics/team.dart';

Map<String, Object> textsArabic = {
  'arabic': 'عربى',
  'english': 'إنجليزى',
  'number of visits': 'عدد الزيارات',
  'must account': 'يجب إنشاء حساب أو تسجيل الدخول',
  'create account': 'إنشاء حساب',
  'log in': 'تسجيل الدخول',
  'agreement': 'هل أنت موافق على شروط سياسة الخصوصية ؟',
  'can see policy': 'يمكنك الإطلاع على شوط الإستخدام و الموافقة عليها',
  'ok': 'موافق',
  'refused': 'لا أوافق',
  'overview': 'عرض',
  'welcome': 'مرحبا بعودتك',
  'welcome text': 'قم بالتسجيل الان و تصفح التطبيق',
  'enter email': 'أدخل البريد الإلكترونى',
  'enter password': 'أدخل كلمة السر',
  'enter name': 'أدخل الاسم الثلاثى باللغة العربية',
  'forget password': 'هل نسيت كلمة السر ؟',
  'sign up new': 'إنشاء حساب جديد',
  'sign up new text': 'قم بإنشاء حساب الان و تصفح التطبيق',
  'forget password title': 'نسيت كلمة السر ؟',
  'forget password text': 'قم بتحديثها الان',
  'enter name in account': 'أدخل الاسم المسجل بحسابك',
  'enter new password': 'أدخل كلمة السر الجديدة',
  'enter confirm password': 'تأكيد كلمة السر الجديدة',
  'update password': 'تحديث كلمة السر',
  'ensure password match': 'يجب التأكد من تطابق كلمة المرور',
  'edit': 'تعديل',
  'accounts': 'حساباتى',
  'enter phone': 'رقم الجوال مع رمز الدولة هذا الرقم لا يظهر للاخرين',
  'enter location': 'أدخل الدولة و المدينة',
  'enter gender': 'أدخل الجنس (ذكر أو أنثى)',
  'enter bio': 'أدخل نبذة تعريفية عنك',
  'enter facebook': 'أدخل رابط الفيس بوك الخاص بك',
  'enter website': 'أدخل الموقع الخاص بك',
  'enter instagram': 'أدخل رابط الإنستجرام الخاص بك',
  'enter twitter': 'أدخل رابط التويتر الخاص بك',
  'enter snapchat': 'أدخل رابط الاسناب شات الخاص بك',
  'enter tiktok': 'أدخل رابط التيك توك الخاص بك',
  'enter age': 'أدخل العمر',
  'enter position': 'المهنة (طالب أو موظف)',
  'update profile information': 'تعديل بيانات حسابك',
  'fav': 'المفضلة',
  'create store': 'إنشاء متجر',
  'search': 'ابحث هنا',
  'store name ar': 'أدخل اسم المتجر بالعربى',
  'store name en': 'أدخل اسم المتجر بالإنجليزى',
  'store location ar': 'أدخل العنوان بالعربى: الدولة المدينة الحي',
  'store location en': 'أدخل العنوان بالإنجليزى: الدولة المدينة الحي',
  'store position link': 'أدخل رابط احداثيات المتجر',
  'store seller number': 'أدخل رقم جوال صاحب المتجر',
  'store number': 'أدخل رقم جوال المتجر',
  'store open': 'وقت فتح المتجر',
  'store close': 'وقت غلق المتجر',
  'store image': 'اختر صورة شعار المتجر',
  'store banners': 'اختر صور إعلانات المتجر إن وجدت',
  'store file': 'اختر ملف السجل التجارى أو الترخيص أو الهوية الوطنية PDF',
  'rate us': 'قيمنا',
  'end com': 'انتهت',
  'ready com': 'لم تبدأ',
  'run com': 'جارى التنفيذ',
  'number com': 'عدد المتسابقين',
  'vote will close': 'سيتم إغلاق التصويت بتاريخ',
  'vote closed': 'تم إغلاق التصويت بتاريخ',
  'vote close today': 'سيتم إغلاق التصويت اليوم',
  'number of vote': 'عدد الأصوات المرشحة من الجماهير',
  'no courses': 'لا يوجد دورات رياضية',
  'create course': 'إنشاء دورة',
  'enter en course': 'أدخل اسم الدورة بالإنجليزية',
  'enter ar course': 'أدخل اسم الدورة بالعربى',
  'enter trainer course ar': 'أدخل مدرب الدورة بالعربى',
  'enter trainer course en': 'أدخل مدرب الدورة بالإنجليزى',
  'enter link course': 'أدخل رابط فيديو الدورة',
  'enter success course': 'أدخل نسبة النجاح بالدورة',
  'start quiz': 'ابدأ بإنشاء أسئلة الدورة',
  'select photo course': 'اختر صورة الدورة',
  'select file course': 'اختر ملف الدورة',
  'quiz num': 'رقم السؤال',
  'finish course': 'الإنتهاء من إنشاء الأسئلة',
  'enter quiz': 'يجب إدخال السؤال',
  'true': 'صح',
  'false': 'خطأ',
  'course name': 'اسم الدورة',
  'your user name': 'اسم المستخدم الخاص بك',
  'day date': 'تاريخ اليوم',
  'course file': 'حمل ملف الدورة',
  'the success rate': 'نسبة النجاح',
  'start questions': 'ابدأ اختبار الدورة',
  'correct exam': 'تصحيح الإختبار',
  'add vote': 'أضف تصويت',
  'comment': 'تعليق',
  'share': 'مشاركة',
  'comments': 'التعليقات',
  'write comment': 'اكتب تعليق...',
  'add comment': 'إضافة تعليق',
  'contact the store': 'التواصل مع المتجر',
  'work hours store': ':ساعات العمل',
  'from': 'من',
  'to': 'إلى',
  'store contact number': 'رقم التواصل مع المتجر:',
  'click here to connect': 'اضغط هنا للتواصل',
  'store address': 'عنوان المتجر:',
  'click to get the store address via coordinates':
      'اضغط للحصول على عنوان المتجر عبر الإحداثيات',
  'sr': 'ر.س',
  'size': 'الحجم',
  'color': 'اللون',
  'product Description': 'وصف المنتج',
  'discount': 'خصم',
  'add cat ar': 'أدخل اسم التصنيف بالعربى',
  'add cat en': 'أدخل اسم التصنيف بالإنجليزى',
  'add cat': 'أضف التصنيف',
  'add cats': 'إضافة تصنيف',
  'delete product': 'حذف المنتج',
  'delete an ad image': 'حذف صورة إعلان',
  'add product': 'إضافة منتج',
  'download game': 'تحميل اللعبة',
  'enter product name': 'أدخل اسم المنتج',
  'enter product description': 'أدخل وصف المنتج',
  'enter product price': 'أدخل سعر المنتج',
  'enter product video': 'أدخل رابط فيديو يوتيوب للمنتج إن وجد',
  'enter product discount': 'أدخل نسبة الخصم على المنتج إن وجد',
  'enter product size': 'اختر حجم المنتج',
  'enter product color': 'اختر لون المنتج',
  'enter product category': 'اختر تصنيف المنتج',
  'enter product image': 'اختر صورة المنتج',
  'create product': 'إضافة المنتج',
  'enter competitor name ar': 'أدخل اسم المتسابق الأول و الأخير بالعربى',
  'enter competitor name en': 'أدخل اسم المتسابق الأول و الأخير بالإنجليزى',
  'enter competitor center ar': 'أدخل مركز المتسابق من كلمتين فقط بالعربى',
  'enter competitor center en': 'أدخل مركز المتسابق من كلمتين فقط بالإنجليزى',
  'enter competitor video link': 'أدخل رابط فيديو يوتيوب فقط',
  'enter competitor country': 'اختر صورة الدولة',
  'enter competitor image': 'اختر صورة المتسابق',
  'enter competitor video': 'اختر فيديو لا يزيد عن 40 ثانيه',
  'share competition': 'شارك بالمسابقة',
  'player name ar': 'أدخل اسم اللاعب بالكامل بالعربى',
  'player name en': 'أدخل اسم اللاعب بالكامل بالإنجليزى',
  'player cv ar': 'أدخل تفاصيل ومعلومات اللاعب بالكامل بالعربى CV',
  'player cv en': 'أدخل تفاصيل ومعلومات اللاعب بالكامل بالإنجليزى CV',
  'player price': 'أدخل المبلغ المطلوب للاعب بالدولار الأمريكى',
  'player agent': 'أدخل  اسم الأكاديمية أو النادى المنتمى له',
  'player country': 'حمل صورة علم دولتك',
  'player country name': 'أدخل اسم دولتك',
  'player image': 'حمل الصورة الشخصية للاعب',
  'post request': 'نشر الطلب',
  'details player name': 'اسم اللاعب',
  'player academy': 'أكاديمية اللاعب',
  'details date': 'تاريخ النشر',
  'details policy 1': 'الذهاب للدردشة مع ناشر الطلب',
  'details policy 2': 'هذا الخبر على مسئولية الناشر',
  'chat users': 'مستخدمين الغرفة',
  'chat users current': 'الموجودون حاليا',
  'chat name ar': 'أدخل اسم المحادثة بالعربى',
  'chat name en': 'أدخل اسم المحادثة بالإنجليزى',
  'chat numbers': 'أدخل عدد مستخدمين المحادثة',
  'chat image': 'اختر صورة المحادثة',
  'create chat': 'قم بإنشاء المحادثة',
  'player marketer': 'التواصل مع اللاعب',
  'report': 'إبلاغ',
  'block': 'حظر',
  'un block': 'إلغاء الحظر',
  'report text': 'اكتب سبب البلاغ',
  "welcome to ifmis start": "التالى",
  "or register": "أو",
  "google": "جوجل",
  "change bg image": "اختر علم الدولة",
  "change your image": "اختر صورة شخصية",
  "open course": "وقت فتح الدورة",
  "close course": "وقت غلق الدورة",
  "type course": "نوع الدورة",
  "type course football": "دورة كرة قدم",
  "type course public": "دورة عامة",
  "notifications": "التنبيهات",
  "scroll delete": "اسحب يمين أو يسار للحذف",
  "confirm code": "أدخل رمز التأكيد",
  "profile": "الملف الشخصي",
  "talent name": "اسم الاعب",
  "talent age": "عمر الاعب",
  "talent school": "مدرسة الاعب",
  "talent position": "وظيفة الاعب",
  "talent height": "طول الاعب",
  "talent class": "الصف الدراسى للاعب",
  "talent support": "التواصل مع الدعم الفني",
  "talent point": "أضف نقاط الفوز",
  "add talent name en": "أدخل اسم الاعب بالإنجليزى",
  "add talent name ar": "أدخل اسم الاعب بالعربى",
  "add talent age": "أدخل عمر الاعب",
  "add talent school": "أدخل اسم مدرسة الاعب",
  "add talent position": "أدخل مركز أو وظيفه الاعب",
  "add talent height": "أدخل طول الاعب",
  "add talent class": "أدخل الصف الدراسى الاعب",
  "add talent video": "أدخل رابط فيديو يوتيوب",
  "add talent images": "اختر صور الاعب",
  "add talent": "أضف المشاركة",
  "serial": "الرقم التسلسلى",
  "add contribution": "اضف مشاركتك",
};

Map<String, Object> textsEnglish = {
  'arabic': 'Arabic',
  'english': 'English',
  'number of visits': 'Number of visits',
  'must account': 'You must create an account or log in',
  'create account': 'Create an account',
  'log in': 'Sign in',
  'agreement': 'Do you agree to the terms of the privacy policy ?',
  'can see policy': 'You can view the terms of use and agree to them',
  'ok': 'OK',
  'refused': 'Refused',
  'overview': 'Overview',
  'welcome': 'welcome back',
  'welcome text': 'Register now and browse the application',
  'enter email': 'Enter email',
  'enter password': 'Enter password',
  'forget password': 'Forgot your password ?',
  'enter name': 'Enter the full name',
  'sign up new': 'Create a new account',
  'sign up new text': 'Create an account now and browse the app',
  'forget password title': 'Forgot your password ?',
  'forget password text': 'Update now',
  'enter name in account': 'Enter the name registered with your account',
  'enter new password': 'Enter new password',
  'enter confirm password': 'Confirm new password',
  'update password': 'Update password',
  'ensure password match': 'You must ensure that the password matches',
  'edit': 'Edit',
  'accounts': 'Accounts',
  'enter phone': 'Mobile number with country code. This number is not visible to others',
  'enter location': 'Enter country and city',
  'enter gender': 'Enter gender(male or female)',
  'enter bio': 'Enter information about you',
  'enter facebook': 'Enter your facebook link',
  'enter website': 'Enter your website link',
  'enter instagram': 'Enter your instagram link',
  'enter twitter': 'Enter your twitter link',
  'enter snapchat': 'Enter your snapchat link',
  'enter tiktok': 'Enter your tiktok link',
  'enter age': 'Enter your age',
  'enter position': 'Profession (student or employee)',
  'enter place': 'Enter the name of the employer',
  'update profile information': 'Edit your account information',
  'fav': 'Favourite',
  'create store': 'Create store',
  'search': 'Search here',
  'store name ar': 'Enter store name with arabic',
  'store name en': 'Enter store name with english',
  'store location ar': 'Enter store location with arabic',
  'store location en': 'Enter store location with english',
  'store position link': 'Enter store position link',
  'store seller number': 'Enter store seller number',
  'store number': 'Enter store number',
  'store open': 'Enter store opening time',
  'store close': 'Enter store closing time',
  'store image': 'Select store image',
  'store banners': 'Select store banners if exist',
  'store file': 'Select the commercial register pdf file',
  'rate us': 'Rate us',
  'end com': 'ended',
  'ready com': 'not started',
  'run com': 'running',
  'number com': 'number of contestants',
  'vote will close': 'Voting will close on',
  'vote closed': 'Voting closed on',
  'vote close today': 'Voting will close today',
  'number of vote': 'Number of fans votes',
  'no courses': 'There are no sports courses',
  'create course': 'Create course',
  'enter en course': 'Enter the course name in English',
  'enter ar course': 'Enter the course name in Arabic',
  'enter trainer course ar': 'Enter trainer course with arabic',
  'enter trainer course en': 'Enter trainer course with english',
  'enter link course': 'Enter the course video link',
  'enter success course': 'Enter success course',
  'start quiz': 'start creating course questions',
  'select photo course': 'select photo course',
  'select file course': 'select file course',
  'quiz num': 'question number',
  'finish course': 'Finish creating questions',
  'enter quiz': 'Question must be entered',
  'true': 'True',
  'false': 'False',
  'course name': 'Course Name',
  'your user name': 'Your user name',
  'day date': 'Day date',
  'course file': 'Course File',
  'the success rate': 'The success rate',
  'start questions': 'Start Quiz',
  'correct exam': 'Correct course',
  'add vote': 'Add Vote',
  'comment': 'Comment',
  'share': 'Share',
  'comments': 'Comments',
  'write comment': 'Write comment...',
  'add comment': 'Add comment',
  'contact the store': 'Contact the store',
  'work hours store': ':work hours',
  'from': 'from',
  'to': 'to',
  'store contact number': 'Store contact number:',
  'click here to connect': 'Click here to connect',
  'store address': 'Store address:',
  'click to get the store address via coordinates':
      'Click to get the store address via coordinates',
  'sr': 'SR',
  'size': 'Size',
  'color': 'Color',
  'product Description': 'Product Description',
  'discount': 'Discount',
  'add cat ar': 'Enter category name with arabic',
  'add cat en': 'Enter category name with english',
  'add cat': 'Add category',
  'add product': 'Add Product',
  'delete product': 'Delete Product',
  'delete an ad image': 'Delete an ad image',
  'add cats': 'Add category',
  'download game': 'Download game',
  'enter product name': 'Enter product name',
  'enter product description': 'Enter product description',
  'enter product price': 'Enter product price',
  'enter product video':
      'Enter the YouTube video link of the product, if available',
  'enter product discount':
      'Enter the discount rate on the product, if available',
  'enter product size': 'Choose the product size',
  'enter product color': 'Choose the product color',
  'enter product category': 'Choose the product category',
  'enter product image': 'Choose the product image',
  'create product': 'Add product',
  'enter competitor name ar': 'Enter competitor name with arabic',
  'enter competitor name en': 'Enter competitor name with english',
  'enter competitor center ar': 'Enter competitor position with arabic',
  'enter competitor center en': 'Enter competitor position with english',
  'enter competitor video link': 'Enter the YouTube video link only',
  'enter competitor country': 'Choose Country image',
  'enter competitor image': 'Choose competitor image',
  'enter competitor video': 'Choose a video no longer than 40 seconds',
  'share competition': 'Share Competition',
  'player name ar': 'Enter player name with arabic',
  'player name en': 'Enter player name with english',
  'player cv ar':
      'Enter the player\'s full CV details and information in Arabic',
  'player cv en':
      'Enter the player\'s full CV details and information in English',
  'player price': 'Enter The amount required for the player in US dollars',
  'player agent': 'Enter The name of the academy or club to which it belongs',
  'player country name': 'Enter your country name',
  'player country': 'Upload a picture of your country\'s flag',
  'player image': 'Enter Upload the player\'s profile picture',
  'post request': 'Post the request',
  'details player name': 'Player name',
  'player academy': 'Player Academy',
  'details date': 'Publish Date',
  'details policy 1': 'Go to chat with the publisher of the news',
  'details policy 2': 'This news is the responsibility of the publisher',
  'chat users': 'number of using the room',
  'chat users current': 'number of present',
  'chat name ar': 'Enter chat name with arabic',
  'chat name en': 'Enter chat name with english',
  'chat numbers': 'Enter numbers of chat\'s users',
  'chat image': 'Select chat image',
  'create chat': 'Create chat',
  'player marketer': 'Connect with the player',
  'report': 'Report',
  'block': 'Block',
  'un block': 'UnBlock',
  'report text': 'Enter Report Reason',
  "welcome to ifmis start": "NEXT",
  "or register": "or",
  "google": "Google",
  "change bg image": "choose country image",
  "change your image": "choose personal image",
  "open course": "course opening time",
  "close course": "course closing time",
  "type course": "course type",
  "type course football": "football course",
  "type course public": "public course",
  "notifications": "Notifications",
  "scroll delete": "swipe right or left to delete",
  "confirm code": "Enter confirmation code",
  "profile": "Profile",
  "talent name": "Player Name",
  "talent age": "Player Age",
  "talent school": "Player School",
  "talent position": "Player Job",
  "talent height": "Player Height",
  "talent class": "Player Class Room",
  "talent support": "Contact with technical support",
  "talent point": "Add Like",
  "add talent name en": "Add player name with english",
  "add talent name ar": "Add player name with arabic",
  "add talent age": "Add player age",
  "add talent school": "Add player school name",
  "add talent position": "Add player job or position",
  "add talent height": "Add player height",
  "add talent class": "Add player class room",
  "add talent video": "Add youtube video link",
  "add talent images": "Add player images",
  "add talent": "Add Post",
  "serial": "Serial Number",
  "add contribution": "Add contribution",
};

List arabic = [
  'ظ',
  'ز',
  'و',
  'ة',
  'آ',
  'ى',
  'لآ',
  'لا',
  'ر',
  'ؤ',
  'ء',
  'ئ',
  'لأ',
  'لإ',
  'إ',
  'أ',
  'ط',
  'ك',
  'م',
  'ن',
  'ت',
  'ا',
  'ل',
  'ب',
  'ي',
  'س',
  'ش',
  'ض',
  'ص',
  'ث',
  'ق',
  'ف',
  'غ',
  'ع',
  'ه',
  'خ',
  'ح',
  'ج',
  'د',
  'ذ',
];

List<ArticlesModel> articles = [];
List<ArticlesModel> otherArticles = [];
List<PlayerModel> players = [];
List<MatchesScoresModel> scores = [];
List<TeamModel> teams = [];
List<PlayerModel> otherPlayers = [];
List<BannerModel> upBanners = [];
List<BannerModel> downBanners = [];
List<ProgrammerModel> programmers = [];
List<ScreensModel> screens = [];
List<SideMenuModel> sideMenu = [];
List<NotificationModel> notifications = [];
late UserModel userModel;
SettingModel settingModel = SettingModel(
  id: 0,
  newsTicker: LanguageModel(en: '', ar: ''),
  intellectualProperty: LanguageModel(en: '', ar: ''),
  membershipTerms: LanguageModel(en: '', ar: ''),
  privacyPolicy: LanguageModel(en: '', ar: ''),
  evacuationResponsibilaty: LanguageModel(en: '', ar: ''),
  vision: LanguageModel(en: '', ar: ''),
  userCount: 0,
  visitors: 0,
  value: '',
  whatsNumber: '',
  storeText: LanguageModel(en: '', ar: ''),
  courseText: LanguageModel(en: '', ar: ''),
  talentText: LanguageModel(en: '', ar: ''),
);
ProgrammerModel programmerModel = ProgrammerModel(
  name: '',
  image: '',
  background: '',
  bio: '',
  linkedIn: '',
  freelancer: '',
  whatsapp: '',
);
