// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbH5sfy63Ewmi3yMnS6liF_UTZC1a1X54',
    appId: '1:647264104279:web:9b1bbbb43b772bbd9ad812',
    messagingSenderId: '647264104279',
    projectId: 'ifmis-b19e1',
    authDomain: 'ifmis-b19e1.firebaseapp.com',
    storageBucket: 'ifmis-b19e1.appspot.com',
    measurementId: 'G-W63QKMFGKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHQmliaAE7ZXGmhnXfvAwzqGkPOVwCWmg',
    appId: '1:647264104279:android:8541e23578d25dd79ad812',
    messagingSenderId: '647264104279',
    projectId: 'ifmis-b19e1',
    storageBucket: 'ifmis-b19e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB6NW95pf5f-1Kru6jtxIlg8Ou_yN28ug',
    appId: '1:647264104279:ios:bc431552d9dbfb299ad812',
    messagingSenderId: '647264104279',
    projectId: 'ifmis-b19e1',
    storageBucket: 'ifmis-b19e1.appspot.com',
    iosBundleId: 'dev.sportimfissport.com',
  );
}
